![title](img/numpy.jpeg)


# Numpy


### What is Numpy

NumPy is the fundamental package for scientific computing with Python. It contains 
- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.
######http://www.numpy.org/

###### Import numpy and matplotlib.pyplot to use them

Matplotlib.pyplot provides a MATLAB-like plotting framework. 
Pylab combines pyplot with numpy into a single namespace. 
This is convenient for interactive work.

######https://matplotlib.org/api/pyplot_api.html#module-matplotlib.pyplot

In [27]:
import numpy as np
import matplotlib.pyplot as plt

## Numpy Random
NumPy provides various routines in the submodule random. It uses a particular algorithm, called the Mersenne Twister, to generate pseudorandom numbers.
######https://www.packtpub.com/mapt/book/big_data_and_business_intelligence/9781785285110/2/ch02lvl1sec16/numpy-random-numbers

##### Array creation
NumPy’s array class is called ndarray. It is also known by the alias array. You can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.
######https://docs.scipy.org/doc/numpy/user/quickstart.html

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
#dtype can also be specified
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [32]:
#1d array
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [33]:
#2d array
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
#3d array
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Normal

In [37]:
#Generate random number
random = np.random.uniform(0.0,10.0)

In [38]:
print(random)

2.5140539554934604


###### numpy.random.sample(size=None)

Return random floats in the half-open interval (0.0, 0.1)
Results are from the “continuous uniform” distribution over the stated interval.

######https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.random_sample.html#numpy.random.random_sample

In [39]:
np.random.random_sample()

0.5270343696287156

In [40]:
np.random.random_sample((5,))

array([0.50078281, 0.73060559, 0.32922319, 0.06806203, 0.13404804])

###### numpy.random.permutation(x)
Randomly permute a sequence, or return a permuted range.

If x is a multi-dimensional array, it is only shuffled along its first index.

Parameters:

x : int or array_like
If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.

Returns:	

out : ndarray
Permuted sequence or array range.

######https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.permutation.html#numpy.random.permutation

In [41]:
np.random.permutation(10)

array([4, 6, 2, 5, 7, 1, 8, 9, 3, 0])

In [42]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 9,  1,  4, 15, 12])

In [43]:
 arr = np.arange(16).reshape((4, 4))

In [44]:
np.random.permutation(arr)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])